/* include/gc_config.h.  Generated by configure.  */
/* include/gc_config.h.in.  Generated from configure.ac by autoheader.  */

/* allows all pointers to the interior of objects to be recognized */
#define ALL_INTERIOR_POINTERS 1

/* include code for GC_malloc_atomic_uncollectable */
#define ATOMIC_UNCOLLECTABLE 1

/* No description */
/* #undef DATASTART_IS_ETEXT */

/* Make sure that all objects have debug headers */
/* #undef DBG_HDRS_ALL */

/* No description */
/* #undef DGUX_THREADS */

/* Target is ECOS */
/* #undef ECOS */

/* support AIX threads */
/* #undef GC_AIX_THREADS */

/* support for Mac OS X pthreads */
#define GC_DARWIN_THREADS 1

/* support for DB/UX on I386 threads */
/* #undef GC_DGUX386_THREADS */

/* support FreeBSD threads */
/* #undef GC_FREEBSD_THREADS */

/* include support for gcj */
#define GC_GCJ_SUPPORT 1

/* enables support for HP/UX 11 pthreads */
/* #undef GC_HPUX_THREADS */

/* support for Irix pthreads */
/* #undef GC_IRIX_THREADS */

/* support for Xavier Leroy's Linux threads */
/* #undef GC_LINUX_THREADS */

/* support for Tru64 pthreads */
/* #undef GC_OSF1_THREADS */

/* support for Solaris pthreads */
/* #undef GC_SOLARIS_PTHREADS */

/* support for Solaris (thr_) threads */
/* #undef GC_SOLARIS_THREADS */

/* support for win32 threads */
/* #undef GC_WIN32_THREADS */

/* ppc_thread_state64_t has field r0 */
/* #undef HAS_PPC_THREAD_STATE64_R0 */

/* ppc_thread_state64_t has field __r0 */
/* #undef HAS_PPC_THREAD_STATE64___R0 */

/* ppc_thread_state_t has field r0 */
/* #undef HAS_PPC_THREAD_STATE_R0 */

/* ppc_thread_state_t has field __r0 */
/* #undef HAS_PPC_THREAD_STATE___R0 */

/* x86_thread_state32_t has field eax */
/* #undef HAS_X86_THREAD_STATE32_EAX */

/* x86_thread_state32_t has field __eax */
#define HAS_X86_THREAD_STATE32___EAX 1

/* x86_thread_state64_t has field rax */
/* #undef HAS_X86_THREAD_STATE64_RAX */

/* x86_thread_state64_t has field __rax */
/* #undef HAS_X86_THREAD_STATE64___RAX */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `pthread_getattr_np' function. */
/* #undef HAVE_PTHREAD_GETATTR_NP */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* make it somewhat safer to finalize objects out of order */
#define JAVA_FINALIZATION 1

/* Add code to save back pointers */
/* #undef KEEP_BACK_PTRS */

/* Enable GC_PRINT_BACK_HEIGHT environment variable */
/* #undef MAKE_BACK_GRAPH */

/* removes GC_dump */
/* #undef NO_DEBUGGING */

/* cause some or all of the heap to not have execute permission */
/* #undef NO_EXECUTE_PERMISSION */

/* Define to 1 if your C compiler doesn't accept -c and -o together. */
/* #undef NO_MINUS_C_MINUS_O */

/* does not disable signals */
#define NO_SIGNALS 1

/* use empty GC_disable_signals and GC_enable_signals */
/* #undef NO_SIGSET */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* allow the marker to run in multiple threads */
/* #undef PARALLEL_MARK */

/* number of call frames saved with objects allocated through the debugging
   interface */
/* #undef SAVE_CALL_COUNT */

/* disables statistics printing */
#define SILENT 1

/* PROC_VDB in Solaris 2.5 gives wrong values for dirty bits */
/* #undef SOLARIS25_PROC_VDB_BUG_FIXED */

/* No description */
/* #undef STACKBASE */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Avoid Solaris 5.3 dynamic library bug */
/* #undef SUNOS53_SHARED_LIB */

/* define GC_local_malloc() & GC_local_malloc_atomic() */
#define THREAD_LOCAL_ALLOC 1

/* use tls for boehm */
/* #undef USE_COMPILER_TLS */

/* use MMAP instead of sbrk to get new memory */
/* #undef USE_MMAP */

/* POSIX version of C Source */
/* #undef _POSIX_C_SOURCE */

/* Required define if using POSIX threads */
/* #undef _REENTRANT */
