/* include/gc_ext_config.h.  Generated by configure.  */
/* include/gc_ext_config.h.in.  This contains definitions needed by
external clients that do not want to include the full gc.h.  Currently this
is used by libjava/include/boehm-gc.h. */

#define THREAD_LOCAL_ALLOC 1

/* #undef HAVE_PTHREAD_GETATTR_NP */
